// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx4UuBycjELgfjkKfkVWZAL6K5ysCOQ64',
    appId: '1:129300036959:web:403a828b3df6dc16660aea',
    messagingSenderId: '129300036959',
    projectId: 'mutualhack-8baad',
    authDomain: 'mutualhack-8baad.firebaseapp.com',
    storageBucket: 'mutualhack-8baad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAehh5ddVxDZQL7lxf2NG3ogS4IJ_0gYU',
    appId: '1:129300036959:android:9c4fcb32d67b7dc6660aea',
    messagingSenderId: '129300036959',
    projectId: 'mutualhack-8baad',
    storageBucket: 'mutualhack-8baad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcHdi1OYSeJ7uTGpnuAvIdrim8pjfAY4',
    appId: '1:129300036959:ios:3b12814c0544bf1a660aea',
    messagingSenderId: '129300036959',
    projectId: 'mutualhack-8baad',
    storageBucket: 'mutualhack-8baad.appspot.com',
    iosBundleId: 'com.example.mutualhack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYcHdi1OYSeJ7uTGpnuAvIdrim8pjfAY4',
    appId: '1:129300036959:ios:0b8e79a25374373c660aea',
    messagingSenderId: '129300036959',
    projectId: 'mutualhack-8baad',
    storageBucket: 'mutualhack-8baad.appspot.com',
    iosBundleId: 'com.example.mutualhack.RunnerTests',
  );
}
